mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", include("users.urls")),
    path("students/", include("students.urls", "students")),
    path("teachers/", include("teachers.urls", "teachers")),
    path('admin/', admin.site.urls),

    # DC - Forgotten Password URLS

    #1 - User Email Submission - Utilizes djangos PasswordResetView (class based view)
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="users/reset_password.html"), name="reset_password"),
    #2 - Email Sent Message - Utilizes django PasswordResetDoneView (class based view)
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="users/reset_password_sent.html"), name="password_reset_done"),
    #3 - Email Link + Reset Instructions - Utilizes PasswordResetConfirmView (class based view)
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/reset.html"), name="password_reset_confirm"),
    #4 - Password Successfully Reset - Utilizes PasswordResetCompleteView (class based view)
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="users/reset_password_complete.html"), name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/students/urls.py
from django.urls import path, re_path


from . import views
app_name = 'students'
urlpatterns = [
    path("", views.home, name="home"),
    path("course/<str:course_id>/", views.course, name="course"),
    path("delete_course/<str:course_id>/", views.deleteCourse, name="deleteCourse"),
    path("discussions/<str:course_id>/", views.discussion, name="discussion"),
    path("post/<str:id>/<str:course_id>/", views.post, name="post"),
    path("delete_post/<str:id>/<str:course_id>/", views.deletePost, name="deletePost"),
    path("module_hub/<str:course_id>/", views.moduleHub, name="moduleHub"),
    path("module_view/<str:id>/<str:course_id>/", views.moduleView, name="moduleView"),
    path("quiz_hub/<str:course_id>/", views.quizHub, name="quizHub"),
    path("quiz/<str:id>/<str:course_id>/", views.quiz, name="quiz"),
    path("quiz_view/<str:id>/<str:course_id>/", views.quizView, name="quizView"),
    re_path(r'^settings/(?P<url>.+)/$', views.settings, name='settings'),
    re_path(r'^change_username/(?P<url>.+)/$', views.changeUsername, name='changeUsername'),
    re_path(r'^change_password/settings/(?P<url>.+)/$', views.changePassword, name='changePassword'),
    path("search/", views.search, name="search"),
    path("student_view/<str:course_id>/", views.studentView, name="studentView"),
    path("student_report/", views.studentReport, name="studentReport"),
    path("past_semester/<str:term>/", views.pastSemester, name="pastSemester"),

    path("anime/", views.anime, name="anime"),
]

mysite/teachers/urls.py
from django.urls import path, re_path


from . import views
app_name = 'teachers'
urlpatterns = [
    path("", views.home, name="home"),
    path("course/<str:course_id>/", views.course, name="course"),
    path("delete_course/<str:course_id>/", views.deleteCourse, name="deleteCourse"),
    path("discussions/<str:course_id>/", views.discussion, name="discussion"),
    path("post/<str:id>/<str:course_id>/", views.post, name="post"),
    path("delete_post/<str:id>/<str:course_id>/", views.deletePost, name="deletePost"),
    path("module_hub/<str:course_id>/", views.moduleHub, name="moduleHub"),
    path("module/<str:id>/<str:course_id>/", views.module, name="module"),
    path("module_view/<str:id>/<str:course_id>/", views.moduleView, name="moduleView"),
    path("module_section/<str:id>/<str:course_id>/", views.moduleSection, name="moduleSection"),
    path("short_answer/<str:id>/<str:course_id>/", views.shortAnswer, name="shortAnswer"),
    path("quiz_hub/<str:course_id>/", views.quizHub, name="quizHub"),
    path("quiz/<str:id>/<str:course_id>/", views.quiz, name="quiz"),
    path("quiz_view/<str:id>/<str:course_id>/", views.quizView, name="quizView"),
    path("options/<str:id>/<str:course_id>/", views.options, name="options"),
    path("module_options/<str:id>/<str:course_id>/", views.moduleOptions, name="moduleOptions"),
    path("submissions/<str:module_id>/<str:course_id>/", views.shortAnswerSubmissions, name="shortAnswerSubmissions"),
    path("delete_quiz/<str:id>/<str:course_id>/", views.deleteQuiz, name="deleteQuiz"),
    path("delete_module/<str:id>/<str:course_id>/", views.deleteModule, name="deleteModule"),
    re_path(r'^settings/(?P<url>.+)/$', views.settings, name='settings'),
    re_path(r'^change_username/(?P<url>.+)/$', views.changeUsername, name='changeUsername'),
    re_path(r'^change_password/settings/(?P<url>.+)/$', views.changePassword, name='changePassword'),
    path("search/", views.search, name="search"),
    path("attempts/<str:id>/<str:course_id>/<int:student_id>/", views.attempts, name="attempts"),
    path("student_view/<str:course_id>/<int:student_id>/", views.studentView, name="studentView"),
    path("attempt_view/<str:course_id>/<str:module_id>/<int:student_id>/<int:attempt>/", views.attemptView, name="attemptView"),
    path("analytics/", views.analytics, name="analytics"),
    path("student_report/<int:student_id>/", views.studentReport, name="studentReport"),
    path("submit_grade/<str:course_id>/", views.submitGrade, name="submitGrade"),
    path("past_semester/<int:student_id>/<str:term>/", views.pastSemester, name="pastSemester"),
    path("module_data/<int:student_id>/<str:module_id>/", views.moduleData, name="moduleData"),
    path("student_module/<int:student_id>/<str:module_id>/", views.studentModule, name="studentModule"),
    path("grade_submission/<int:id>/", views.gradeSubmission, name="gradeSubmission"),
    path("delete_section/<int:section_id>/", views.deleteSection, name="deleteSection"),
    path("delete_shortanswer/<str:id>/", views.deleteShortAnswer, name="deleteShortAnswer"),
    path("delete_multichoice/<str:id>/", views.deleteMultiChoice, name="deleteMultiChoice"),
    path('screen1/', views.screen1, name='screen1'),
    path('animation1/', views.animation1, name='animation1'),
]   

mysite/users/urls.py
from django.urls import path

from . import views
app_name = 'users'
urlpatterns = [
    path("register/", views.register, name="register"),
    path("", views.loginPage, name="loginPage"),
    path("logout/", views.logoutPage, name="logoutPage"),
]

mysite/students/models.py
from django.db import models

# Create your models here.

mysite/teachers/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import MyClass

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'username'}),
            'email': forms.EmailInput(attrs={'placeholder': 'email'}),
            'password1': forms.PasswordInput(render_value=True, attrs={'placeholder': 'Enter your password'}),
            'password2': forms.PasswordInput(render_value=True, attrs={'placeholder': 'Confirm your password'}),
        }

class MyClassForm(forms.ModelForm):
    class Meta:
        model = MyClass
        fields = ['class_name', 'class_descriptor']

class EnrollForm(forms.Form):
    enrolled_users = forms.ModelMultipleChoiceField(
        queryset=User.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
        

mysite/students/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Max, OuterRef, Subquery
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from teachers.forms import MyClassForm
from teachers.models import FinalGrade, MyClass, EnrolledUser, Discussion, Reply, Quiz, Question, Grade, Alert, StudentQuestion, Module, ModuleQuestion, ModuleSection, ShortAnswer, StudentShortAnswer, ModuleImage
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
# Create your views here.
class CustomStudent:
    def __init__(self, student, average):
        self.student = student
        self.average = average

class CustomGrade:
    def __init__(self, module, grades):
        self.module = module
        self.grades = grades

class CustomAnalytics:
    def __init__(self, course, grades, grade_counts=None):
        self.course = course
        self.grades = grades
        self.grade_counts = grade_counts

def search(request):
    courses = []
    enrolled_courses = EnrolledUser.objects.filter(user=request.user)
    for course in enrolled_courses:
        courses.append(course.course)
    
    if request.method == 'POST':
        subject = request.POST.get('subject')
        quizzes = Quiz.objects.filter(course__in=courses, title__contains = subject)
        classes = (MyClass.objects.filter(teacher=request.user, class_name__contains=subject) | 
        MyClass.objects.filter(teacher=request.user, class_descriptor__contains=subject))
        discussions = Discussion.objects.filter(course__in=courses, subject__contains = subject)

    context = {'subject':subject, 'quizzes':quizzes, 'classes':classes, 'discussions':discussions}
    return render(request, "students/search.html", context)

def home(request):
    classes = []
    form = MyClassForm()

    if request.method == 'POST':
        form = MyClassForm(request.POST)
        if form.is_valid():
            course = form.save(commit=False)
            course.teacher = request.user
            course.save()
    enrolled_courses = EnrolledUser.objects.filter(user=request.user)
    for course in enrolled_courses:
        classes.append(course.course)
    context = {'form':form, 'classes': classes}
    return render(request, "students/home.html", context)

def course(request, course_id):
    my_class = MyClass.objects.get(id=course_id)
    alerts = Alert.objects.filter(student=request.user, course=my_class).count()
    if request.method == 'POST':
        enrolled_user_ids = request.POST.getlist('enrolled_users')  # Get a list of selected user IDs
        enrolled_users = User.objects.filter(id__in=enrolled_user_ids)
        for user in enrolled_users:
            EnrolledUser.objects.create(user=user, course=my_class)
    users = User.objects.all()
    context = {'courseId': course_id, 'users': users, 'my_class': my_class, 'alerts':alerts}
    return render(request, "students/course.html", context)

def deleteCourse(request, course_id):
    course = MyClass.objects.get(pk=course_id)
    course.delete()
    return redirect('students:home')
    
class CustomGrade:
    def __init__(self, module, grades):
        self.module = module
        self.grades = grades

def studentView(request, course_id):
    course = MyClass.objects.get(pk=course_id)
    student = request.user
    custom_grades = []
    average = 0
    weighting_factor = 0
    subquery = Grade.objects.filter(
        student=student,
        module=OuterRef('pk')  # Use OuterRef to reference the quiz being considered
    ).values('module')

    modules = Module.objects.filter(
        course=course,
        pk__in=Subquery(subquery)
    )
    for module in modules:
        grades = Grade.objects.filter(module=module, student=student)
        max_grade = Grade.objects.filter(module=module, student=student).order_by('-grade').first()
        average += (max_grade.grade * max_grade.module.weight)
        weighting_factor += max_grade.module.weight
        custom_grades.append(CustomGrade(module, grades))
    if(len(modules) > 0):
        average = round(average / weighting_factor, 2)
    context = {'courseId': course_id, 'grades': custom_grades, 'average': average}
    return render(request, "students/studentview.html", context)

def discussion(request, course_id):
    my_class = MyClass.objects.get(id=course_id)
    messages = Discussion.objects.filter(course=my_class).order_by('-created_at')
    enrolled_users = EnrolledUser.objects.filter(course=my_class)
    alerts = Alert.objects.filter(student=request.user, course=my_class)
    alerts.delete()
    if request.method == 'POST':
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        uploaded_file = request.FILES.get('upload')
        post = Discussion.objects.create(
            course=my_class, 
            author=request.user, 
            subject=subject, 
            message=message,
            file=uploaded_file 
        )
        for user in enrolled_users:
            Alert.objects.create(
                course=my_class,
                student=user.user,
                post= post
            )
        return redirect(reverse('students:discussion', args=[course_id]))
        
    context = {'courseId': course_id, 'my_class': my_class, 'messages': messages}
    return render(request, "students/discussion.html", context)

def post(request, id, course_id):
    post = Discussion.objects.get(pk=id)
    fileName = post.file.name.split("/")[-1]
    replies = Reply.objects.filter(post=post).order_by('-created_at')
    if request.method == 'POST':
        message = request.POST.get('message')
        Reply.objects.create(post=post, author=request.user, message=message)
        return redirect(reverse('students:post', args=[id, course_id]))
    context = {'post':post, 'replies':replies, 'courseId':course_id, 'fileName':fileName}
    return render(request, "students/post.html", context)


def deletePost(request, id, course_id):
    post = Discussion.objects.get(pk=id)
    post.delete()
    return redirect(reverse('students:discussion', args=[course_id]))

def moduleHub(request, course_id):
    my_class = MyClass.objects.get(id=course_id)
    modules = Module.objects.filter(course=my_class).order_by('-created_at')
        
    context = {'courseId': course_id, 'my_class': my_class, 'modules': modules}
    return render(request, "students/modulehub.html", context)

def moduleView(request, id, course_id):
    module = Module.objects.get(pk=id)
    questions = ModuleQuestion.objects.filter(module=module)
    sections = ModuleSection.objects.filter(module=module)
    shortAnswers = ShortAnswer.objects.filter(module=module)
    section_objects = []
    for section in sections:
        section_images = ModuleImage.objects.filter(section=section)
        section_objects.append({"section": section, "images": section_images})

    max_section = 0
    max_question = 0
    max_shortAnswer = 0
    if sections.exists():
        max_section = sections.order_by('-position').first().position
    if questions.exists():
        max_question = questions.order_by('-position').first().position
    if shortAnswers.exists():
        max_shortAnswer = shortAnswers.order_by('-position').first().position
    position = max(max_section,max_question,max_shortAnswer) + 1
    
    all_questions = []
    i = 0
    j = 0
    while i < questions.count() and j < shortAnswers.count():
        if questions[i].position < shortAnswers[j].position:
            all_questions.append({"type":"multi", "question":questions[i]})
            i += 1 
        else:
            all_questions.append({"type":"short", "question": shortAnswers[j]})
            j += 1
    while i < questions.count():
        all_questions.append({"type":"multi", "question":questions[i]})
        i += 1 
    while j < shortAnswers.count():
        all_questions.append({"type":"short", "question": shortAnswers[j]})
        j += 1
    
    attempt = 0 
    try:
        grades = Grade.objects.filter(module=module, student=request.user)
        attempt = len(grades)
        # Annotate the query with the maximum grade
        grades = grades.annotate(max_grade=Max('grade'))
        # Order the results in descending order by the maximum grade
        highest_grade = grades.order_by('-max_grade').first()
    except ObjectDoesNotExist:
        grades = None
        highest_grade = None

    if request.method == 'POST':
        total_questions = questions.count() + shortAnswers.count()
        correct = 0
        for question in shortAnswers:
            answer = request.POST.get(f"{question.id}")
            StudentShortAnswer.objects.create(
                module=module,
                student=request.user,
                question_text=question.question_text,
                answer=answer,
                attempt=attempt + 1,
                pending=True
            )
        for question in questions:
            selected_answer = int(request.POST.get(f"{question.id}"))
            StudentQuestion.objects.create(
                module=module,
                student=request.user,
                module_question=question,
                selected_answer=selected_answer,
                correct_answer=question.correct_answer,
                attempt=attempt + 1
            )
            if selected_answer == question.correct_answer:
                correct += 1
        total = (correct/total_questions) * 100
        pending = True
        if shortAnswers.count() == 0:
            pending = False

        Grade.objects.create(
            grade = total,
            module=module, 
            student=request.user,
            attempt = attempt + 1,
            pending= pending
        )
        return redirect(reverse('students:moduleView', args=[id, course_id]))
    

mysite/teachers/templates/teachers/analytics.html
{% extends 'teachers/base.html' %}
{% load static %}

{% block title %}Elearn{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/analytics.css' %}">
{% endblock %}

{% block content %}
<div id="coursediv">
    <div id="grades-wrapper" >
        {% for student in students %}
            <div class="grades" data-class-studentId= "{{ student.id }}">
                <span>{{student.username}}</span> 
            </div>
        {% endfor %}
    </div>
    <div id="close">Close</div>
</div>
<div id="contentwrapper">
    <div id="content">
        <div class="student-button" id="search-students">Search By Students</div>
        <div class="analytics-wrapper">
            {% for grade in grades %}
                {% if grade.grades %}
                    <h1 class="course-title">{{grade.course.class_name}}</h1>
                    <canvas class="pie-chart" id="chart-{{ grade.course.id }}" ></canvas>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

<script src="{% static 'teachers/js/analytics.js' %}"></script>

{% endblock %}

mysite/teachers/templates/teachers/attempts.html
{% extends 'teachers/base.html' %}
{% load static %}

{% block title %}Elearn{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/course.css' %}">
{% endblock %}

{% block content %}
    <a class="backbtn" href="{% url 'teachers:quiz' quiz.id courseId%}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 18h3.75a5.25 5.25 0 1 0 0-10.5H5M7.5 4L4 7.5L7.5 11"/></svg></a> 
    <a class="backbtn" id="homebtn" href="{% url 'teachers:course' courseId%}"><svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024"><path fill="currentColor" d="M946.5 505L534.6 93.4a31.93 31.93 0 0 0-45.2 0L77.5 505c-12 12-18.8 28.3-18.8 45.3c0 35.3 28.7 64 64 64h43.4V908c0 17.7 14.3 32 32 32H448V716h112v224h265.9c17.7 0 32-14.3 32-32V614.3h43.4c17 0 33.3-6.7 45.3-18.8c24.9-25 24.9-65.5-.1-90.5z"/></svg></a>
    <div id="delete-btn" data-class-id= "{{ post.id }}" data-class-courseId= "{{ courseId }}">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" stroke="white" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 6L6 18M6 6l12 12"/></svg>
    </div>
    <div id="coursediv" style="display: block;">
        <div id="grades-wrapper" >
            {% for grade in grades %}
                <div class="grades">
                    attempt: {{grade.attempt}}
                    <span>{{grade.student.username}}</span> 
                    <span>{{grade.grade}}</span> 
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

mysite/teachers/templates/teachers/attemptview.html
{% extends 'teachers/base.html' %}
{% load static %}

{% block title %}Elearn{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/studentview.css' %}">
{% endblock %}

{% block content %}
    <a class="backbtn" href="{% url 'teachers:studentView' courseId studentId %}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 18h3.75a5.25 5.25 0 1 0 0-10.5H5M7.5 4L4 7.5L7.5 11"/></svg></a> 
    <a class="backbtn" id="homebtn" href="{% url 'teachers:course' courseId%}"><svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024"><path fill="currentColor" d="M946.5 505L534.6 93.4a31.93 31.93 0 0 0-45.2 0L77.5 505c-12 12-18.8 28.3-18.8 45.3c0 35.3 28.7 64 64 64h43.4V908c0 17.7 14.3 32 32 32H448V716h112v224h265.9c17.7 0 32-14.3 32-32V614.3h43.4c17 0 33.3-6.7 45.3-18.8c24.9-25 24.9-65.5-.1-90.5z"/></svg></a>
    <div id="contentwrapper">
        <div id="content">
            <div id="wrapper">
                <h2>{{module.title}}</h2>
                <table id="grade-table">
                    <tr>
                        <th>Question</th>
                        <th>Correct Answer</th>
                        <th>Selected Answer</th>
                        <th>Options</th>
                    </tr>
                    {% for question in questions %}
                        <tr>
                            <td>{{question.module_question.question_text}}</td>
                            <td>{{question.correct_answer}}</td>
                            <td>{{question.selected_answer}}</td>
                            <td>{{question.module_question.option1}} <br>
                                {{question.module_question.option2}} <br>
                                {{question.module_question.option3}} <br>
                                {{question.module_question.option4}}
                            </td>
                        </tr>
                    {% endfor %}
                    {% for shortAnswer in shortAnswers %}
                        <tr>
                            <td>{{shortAnswer.question_text}}</td>
                            {% if shortAnswer.grade %}
                                <td>{{shortAnswer.grade}}%</td>
                            {% else %}
                                <td>Needs Grading</td>
                            {% endif %}
                            <td>{{shortAnswer.answer}}</td>
                            <td>Null</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

mysite/teachers/templates/teachers/course.html
{% extends 'teachers/base.html' %}
{% load static %}

{% block title %}ELearn{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/course.css' %}">
{% endblock %}

{% block content %}
    <div id="coursediv">
        <form method="post">
            {% csrf_token %}
            <div id="formwrapper">
                {% for user in users %}
                <div class="inputs">
                    <label class="users" for="{{ user.user.id }}">{{ user.user.username }}</label>
                    <span>
                        <input type="checkbox" id="{{ user.user.id }}" name="enrolled_users" value="{{ user.user.id }}">
                    </span>
                    <br>
                </div>

            {% endfor %}
            </div>
            <button id="enrollbtn" class="button" type="submit">Enroll Selected Users</button>
        </form>
    </div>
    <div id="coursediv-alert">
        <div id="alert-wrapper">
            <span>Do You Want to Submit Final Grades?</span>
            <div class="finalgrade-button">
                <a href="{% url 'teachers:submitGrade' courseId %}" class="close" id="yes">Yes</a>
                <a href="{% url 'teachers:deleteCourse' courseId %}" class="close">No</a>
            </div>
        </div>
        <div class="close" id="close">Close</div>
    </div>
    <div id="coursediv-grades">
        <div class="grade-modifiers">
            <select id="sortOrder" onchange="sortStudents()">
                <option value="desc">Descending</option>
                <option value="asc">Ascending</option>
            </select>
            <span id="average">Weighted Average</span>
        </div>
        <div id="grades-wrapper" >
            {% for student in students %}
                <div class="grades" data-class-courseId= "{{ courseId }}" data-class-studentId= "{{ student.student.user.id }}">
                    <span>{{student.student.user.username}}</span> 
                    <span>{{student.average}}%</span> 
                </div>
            {% endfor %}
        </div>
        <div class="close">Close</div>
    </div>
    <div id="contentwrapper">
        <div id="content">
            <div id="classtitle"><h2>{{my_class.class_name}}</h2></div>
            <div id="tagwrapper">
                <div id="buttons">
                    <div class="button" id="delete">Delete</div>
                    <div class="button" id="addstudents">Add Students</div>
                </div>
                <a class="tags" href="{% url 'teachers:discussion' courseId %}">Discussions</a>
                <a class="tags" href="{% url 'teachers:moduleHub' courseId %}">Modules</a>
                <a class="tags" href="{% url 'teachers:quizHub' courseId %}">Quizes</a>
                <div class="tags" id="grades-link">Grades</div>
                <span>{{courseId}}</span>
            </div>
        </div>
    </div>

    <script src="{% static 'teachers/js/course.js' %}"></script>
{% endblock %}

mysite/teachers/templates/teachers/quiz.html
{% extends 'teachers/base.html' %}
{% load static %}

{% block title %}Home Page{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/course.css' %}">
{% endblock %}

{% block content %}
    <div id="delete-btn" data-class-id= "{{ quiz.id }}" data-class-courseId= "{{ courseId }}">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" stroke="white" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 6L6 18M6 6l12 12"/></svg>
    </div>
    <a class="backbtn" href="{% url 'teachers:quizHub' courseId%}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 18h3.75a5.25 5.25 0 1 0 0-10.5H5M7.5 4L4 7.5L7.5 11"/></svg></a>
    <a class="backbtn" id="homebtn" href="{% url 'teachers:course' courseId%}"><svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024"><path fill="currentColor" d="M946.5 505L534.6 93.4a31.93 31.93 0 0 0-45.2 0L77.5 505c-12 12-18.8 28.3-18.8 45.3c0 35.3 28.7 64 64 64h43.4V908c0 17.7 14.3 32 32 32H448V716h112v224h265.9c17.7 0 32-14.3 32-32V614.3h43.4c17 0 33.3-6.7 45.3-18.8c24.9-25 24.9-65.5-.1-90.5z"/></svg></a>
    <div id="coursediv">
        <div id="grades-wrapper" >
            {% for grade in grades %}
                <div class="grades" data-class-id= "{{ quiz.id }}" data-class-courseId= "{{ courseId }}" data-class-studentId= "{{ grade.student.id }}">
                    <span>{{grade.student.username}}</span> 
                    <span>{{grade.grade}}</span> 
                </div>
            {% endfor %}
        </div>
        <div id="close">Close</div>
    </div>
    <div id="contentwrapper">
        <div id="content">
            <div id="tagwrapper">
                <h2>{{quiz.title}}</h2>
                <a class="tags" href="{% url 'teachers:quizView' quiz.id courseId %}">Quiz View</a>
                <div class="tags" id="grades-link">Grades</div>
                <a class="tags" href="{% url 'teachers:options' quiz.id courseId %}">options</a>
                <span>{{quiz.id}}</span>
            </div>
        </div>
    </div>

    <script src="{% static 'teachers/js/quiz.js' %}"></script>
{% endblock %}