mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", include("users.urls")),
    path("students/", include("students.urls", "students")),
    path("teachers/", include("teachers.urls", "teachers")),
    path('admin/', admin.site.urls),

    # DC - Forgotten Password URLS

    #1 - User Email Submission - Utilizes djangos PasswordResetView (class based view)
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="users/reset_password.html"), name="reset_password"),
    #2 - Email Sent Message - Utilizes django PasswordResetDoneView (class based view)
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="users/reset_password_sent.html"), name="password_reset_done"),
    #3 - Email Link + Reset Instructions - Utilizes PasswordResetConfirmView (class based view)
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/reset.html"), name="password_reset_confirm"),
    #4 - Password Successfully Reset - Utilizes PasswordResetCompleteView (class based view)
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="users/reset_password_complete.html"), name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/students/urls.py
from django.urls import path, re_path


from . import views
app_name = 'students'
urlpatterns = [
    path("", views.home, name="home"),
    path("course/<str:course_id>/", views.course, name="course"),
    path("delete_course/<str:course_id>/", views.deleteCourse, name="deleteCourse"),
    path("discussions/<str:course_id>/", views.discussion, name="discussion"),
    path("post/<str:id>/<str:course_id>/", views.post, name="post"),
    path("delete_post/<str:id>/<str:course_id>/", views.deletePost, name="deletePost"),
    path("module_hub/<str:course_id>/", views.moduleHub, name="moduleHub"),
    path("module_view/<str:id>/<str:course_id>/", views.moduleView, name="moduleView"),
    path("quiz_hub/<str:course_id>/", views.quizHub, name="quizHub"),
    path("quiz/<str:id>/<str:course_id>/", views.quiz, name="quiz"),
    path("quiz_view/<str:id>/<str:course_id>/", views.quizView, name="quizView"),
    re_path(r'^settings/(?P<url>.+)/$', views.settings, name='settings'),
    re_path(r'^change_username/(?P<url>.+)/$', views.changeUsername, name='changeUsername'),
    re_path(r'^change_password/settings/(?P<url>.+)/$', views.changePassword, name='changePassword'),
    path("search/", views.search, name="search"),
    path("student_view/<str:course_id>/", views.studentView, name="studentView"),
    path("student_report/", views.studentReport, name="studentReport"),
    path("past_semester/<str:term>/", views.pastSemester, name="pastSemester"),

    path("anime/", views.anime, name="anime"),
]

mysite/users/urls.py
from django.urls import path

from . import views
app_name = 'users'
urlpatterns = [
    path("register/", views.register, name="register"),
    path("", views.loginPage, name="loginPage"),
    path("logout/", views.logoutPage, name="logoutPage"),
]

mysite/students/models.py
from django.db import models

# Create your models here.

mysite/students/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Max, OuterRef, Subquery
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from teachers.forms import MyClassForm
from teachers.models import FinalGrade, MyClass, EnrolledUser, Discussion, Reply, Quiz, Question, Grade, Alert, StudentQuestion, Module, ModuleQuestion, ModuleSection, ShortAnswer, StudentShortAnswer, ModuleImage
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
# Create your views here.
class CustomStudent:
    def __init__(self, student, average):
        self.student = student
        self.average = average

class CustomGrade:
    def __init__(self, module, grades):
        self.module = module
        self.grades = grades

class CustomAnalytics:
    def __init__(self, course, grades, grade_counts=None):
        self.course = course
        self.grades = grades
        self.grade_counts = grade_counts

def search(request):
    courses = []
    enrolled_courses = EnrolledUser.objects.filter(user=request.user)
    for course in enrolled_courses:
        courses.append(course.course)
    
    if request.method == 'POST':
        subject = request.POST.get('subject')
        quizzes = Quiz.objects.filter(course__in=courses, title__contains = subject)
        classes = (MyClass.objects.filter(teacher=request.user, class_name__contains=subject) | 
        MyClass.objects.filter(teacher=request.user, class_descriptor__contains=subject))
        discussions = Discussion.objects.filter(course__in=courses, subject__contains = subject)

    context = {'subject':subject, 'quizzes':quizzes, 'classes':classes, 'discussions':discussions}
    return render(request, "students/search.html", context)

def home(request):
    classes = []
    form = MyClassForm()

    if request.method == 'POST':
        form = MyClassForm(request.POST)
        if form.is_valid():
            course = form.save(commit=False)
            course.teacher = request.user
            course.save()
    enrolled_courses = EnrolledUser.objects.filter(user=request.user)
    for course in enrolled_courses:
        classes.append(course.course)
    context = {'form':form, 'classes': classes}
    return render(request, "students/home.html", context)

def course(request, course_id):
    my_class = MyClass.objects.get(id=course_id)
    alerts = Alert.objects.filter(student=request.user, course=my_class).count()
    if request.method == 'POST':
        enrolled_user_ids = request.POST.getlist('enrolled_users')  # Get a list of selected user IDs
        enrolled_users = User.objects.filter(id__in=enrolled_user_ids)
        for user in enrolled_users:
            EnrolledUser.objects.create(user=user, course=my_class)
    users = User.objects.all()
    context = {'courseId': course_id, 'users': users, 'my_class': my_class, 'alerts':alerts}
    return render(request, "students/course.html", context)

def deleteCourse(request, course_id):
    course = MyClass.objects.get(pk=course_id)
    course.delete()
    return redirect('students:home')
    
class CustomGrade:
    def __init__(self, module, grades):
        self.module = module
        self.grades = grades

def studentView(request, course_id):
    course = MyClass.objects.get(pk=course_id)
    student = request.user
    custom_grades = []
    average = 0
    weighting_factor = 0
    subquery = Grade.objects.filter(
        student=student,
        module=OuterRef('pk')  # Use OuterRef to reference the quiz being considered
    ).values('module')

    modules = Module.objects.filter(
        course=course,
        pk__in=Subquery(subquery)
    )
    for module in modules:
        grades = Grade.objects.filter(module=module, student=student)
        max_grade = Grade.objects.filter(module=module, student=student).order_by('-grade').first()
        average += (max_grade.grade * max_grade.module.weight)
        weighting_factor += max_grade.module.weight
        custom_grades.append(CustomGrade(module, grades))
    if(len(modules) > 0):
        average = round(average / weighting_factor, 2)
    context = {'courseId': course_id, 'grades': custom_grades, 'average': average}
    return render(request, "students/studentview.html", context)

def discussion(request, course_id):
    my_class = MyClass.objects.get(id=course_id)
    messages = Discussion.objects.filter(course=my_class).order_by('-created_at')
    enrolled_users = EnrolledUser.objects.filter(course=my_class)
    alerts = Alert.objects.filter(student=request.user, course=my_class)
    alerts.delete()
    if request.method == 'POST':
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        uploaded_file = request.FILES.get('upload')
        post = Discussion.objects.create(
            course=my_class, 
            author=request.user, 
            subject=subject, 
            message=message,
            file=uploaded_file 
        )
        for user in enrolled_users:
            Alert.objects.create(
                course=my_class,
                student=user.user,
                post= post
            )
        return redirect(reverse('students:discussion', args=[course_id]))
        
    context = {'courseId': course_id, 'my_class': my_class, 'messages': messages}
    return render(request, "students/discussion.html", context)

def post(request, id, course_id):
    post = Discussion.objects.get(pk=id)
    fileName = post.file.name.split("/")[-1]
    replies = Reply.objects.filter(post=post).order_by('-created_at')
    if request.method == 'POST':
        message = request.POST.get('message')
        Reply.objects.create(post=post, author=request.user, message=message)
        return redirect(reverse('students:post', args=[id, course_id]))
    context = {'post':post, 'replies':replies, 'courseId':course_id, 'fileName':fileName}
    return render(request, "students/post.html", context)


def deletePost(request, id, course_id):
    post = Discussion.objects.get(pk=id)
    post.delete()
    return redirect(reverse('students:discussion', args=[course_id]))

def moduleHub(request, course_id):
    my_class = MyClass.objects.get(id=course_id)
    modules = Module.objects.filter(course=my_class).order_by('-created_at')
        
    context = {'courseId': course_id, 'my_class': my_class, 'modules': modules}
    return render(request, "students/modulehub.html", context)

def moduleView(request, id, course_id):
    module = Module.objects.get(pk=id)
    questions = ModuleQuestion.objects.filter(module=module)
    sections = ModuleSection.objects.filter(module=module)
    shortAnswers = ShortAnswer.objects.filter(module=module)
    section_objects = []
    for section in sections:
        section_images = ModuleImage.objects.filter(section=section)
        section_objects.append({"section": section, "images": section_images})

    max_section = 0
    max_question = 0
    max_shortAnswer = 0
    if sections.exists():
        max_section = sections.order_by('-position').first().position
    if questions.exists():
        max_question = questions.order_by('-position').first().position
    if shortAnswers.exists():
        max_shortAnswer = shortAnswers.order_by('-position').first().position
    position = max(max_section,max_question,max_shortAnswer) + 1
    
    all_questions = []
    i = 0
    j = 0
    while i < questions.count() and j < shortAnswers.count():
        if questions[i].position < shortAnswers[j].position:
            all_questions.append({"type":"multi", "question":questions[i]})
            i += 1 
        else:
            all_questions.append({"type":"short", "question": shortAnswers[j]})
            j += 1
    while i < questions.count():
        all_questions.append({"type":"multi", "question":questions[i]})
        i += 1 
    while j < shortAnswers.count():
        all_questions.append({"type":"short", "question": shortAnswers[j]})
        j += 1
    
    attempt = 0 
    try:
        grades = Grade.objects.filter(module=module, student=request.user)
        attempt = len(grades)
        # Annotate the query with the maximum grade
        grades = grades.annotate(max_grade=Max('grade'))
        # Order the results in descending order by the maximum grade
        highest_grade = grades.order_by('-max_grade').first()
    except ObjectDoesNotExist:
        grades = None
        highest_grade = None

    if request.method == 'POST':
        total_questions = questions.count() + shortAnswers.count()
        correct = 0
        for question in shortAnswers:
            answer = request.POST.get(f"{question.id}")
            StudentShortAnswer.objects.create(
                module=module,
                student=request.user,
                question_text=question.question_text,
                answer=answer,
                attempt=attempt + 1,
                pending=True
            )
        for question in questions:
            selected_answer = int(request.POST.get(f"{question.id}"))
            StudentQuestion.objects.create(
                module=module,
                student=request.user,
                module_question=question,
                selected_answer=selected_answer,
                correct_answer=question.correct_answer,
                attempt=attempt + 1
            )
            if selected_answer == question.correct_answer:
                correct += 1
        total = (correct/total_questions) * 100
        pending = True
        if shortAnswers.count() == 0:
            pending = False

        Grade.objects.create(
            grade = total,
            module=module, 
            student=request.user,
            attempt = attempt + 1,
            pending= pending
        )
        return redirect(reverse('students:moduleView', args=[id, course_id]))
    

mysite/students/templates/students/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Stem Tree{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
        {% block extra_css %}

        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    </head>
    <body>
        <header>
            <nav class="navbar">
                <h2 class="logo"><a href="{% url 'students:home' %}">Stem Tree</a></h2>
                <ul class="all-links">
                    <li id="username"><span>Hello,  {{request.user}}</span></li>
                    <li>
                        <li>
                            <form class="nav-form" method="post" action="{% url 'students:search' %}">
                                {% csrf_token %}
                                <input
                                    type="text"
                                    name="subject"
                                    id="subject"
                                    placeholder="Search"
                                    class="nav-textarea-input"
                                />
                                <button class="nav-btn">
                                    Search
                                </button>
                            </form>
                        </li>
                    </li>
                    <li><a href="{% url 'students:studentReport' %}">Grades</a></li>
                    <li><a href="{% url 'students:settings' request.path%}">Settings</a></li>
                    <li><a href="{% url 'users:logoutPage' %}">Logout</a></li>
                    <li id="bell-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M4 19v-2h2v-7q0-2.075 1.25-3.688T10.5 4.2v-.7q0-.625.438-1.063T12 2q.625 0 1.063.438T13.5 3.5v.7q2 .5 3.25 2.113T18 10v7h2v2H4Zm8 3q-.825 0-1.413-.588T10 20h4q0 .825-.588 1.413T12 22Z"/></svg>
                    </li>                
                </ul>
            </nav>
        </header>
        {% block content %}
        
        {% endblock %}
    </body>
</html>

mysite/students/templates/students/course.html
{% extends 'students/base.html' %}
{% load static %}

{% block title %}Elearn{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/course.css' %}">
{% endblock %}

{% block content %}
    <div id="contentwrapper">
        <div id="content">
            <div id="classtitle"><h2>{{my_class.class_name}}</h2></div>
            <div id="tagwrapper">
                <a class="tags" href="{% url 'students:discussion' courseId %}">
                    {% if alerts > 0 %}
                        <div id="alerts">
                            {{alerts}}
                        </div>
                    {% endif %}
                    Discussions
                </a>
                <a class="tags" href="{% url 'students:moduleHub' courseId %}">Modules</a>
                <a class="tags" href="{% url 'students:quizHub' courseId %}">Quizzes</a>
                <a class="tags" href="{% url 'students:studentView' courseId %}">Grades</a>
                <span>{{courseId}}</span>
            </div>
        </div>
    </div>

    <script src="{% static 'js/course.js' %}"></script>
{% endblock %}

mysite/students/templates/students/moduleview.html
{% extends 'students/base.html' %}
{% load static %}

{% block title %}StemTree{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/moduleview.css' %}">
{% endblock %}

{% block content %}
    <a class="backbtn" href="{% url 'students:moduleHub' courseId%}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 18h3.75a5.25 5.25 0 1 0 0-10.5H5M7.5 4L4 7.5L7.5 11"/></svg></a>
    <a class="backbtn" id="homebtn" href="{% url 'students:course' courseId%}"><svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024"><path fill="currentColor" d="M946.5 505L534.6 93.4a31.93 31.93 0 0 0-45.2 0L77.5 505c-12 12-18.8 28.3-18.8 45.3c0 35.3 28.7 64 64 64h43.4V908c0 17.7 14.3 32 32 32H448V716h112v224h265.9c17.7 0 32-14.3 32-32V614.3h43.4c17 0 33.3-6.7 45.3-18.8c24.9-25 24.9-65.5-.1-90.5z"/></svg></a>
    
    <div id="contentwrapper">
        <div id="content" data-class-studentId= "{{ request.user.id }}" data-class-moduleId= "{{ module.id }}">
            <div id="grade-wrapper" {% if not grade %}style="display: none;"{% endif %}>
                
                <h2>Attempt: {{attempt}}/{{module.attempts}} <br>
                    Your Grade: 
                    {% if grade.pending %}
                        Pending
                    {% else %}
                        {{grade.grade}}%
                    {% endif %}
                </h2>
                {% if attempt < module.attempts %}
                    <div class="btn" id="new-submission">New Submission</div>
                {% endif %}
            </div>
            <div id="wrapper" {% if grade %}style="display: none;"{% endif %}>
                <h2>{{module.title}}</h2>
                <div id="quiz-wrapper-student">
                    <form class="viewForm" method="post">
                        {% csrf_token %}
                        {% for i in count %}
                            {% for section in sections %}
                                {% if section.section.position == i %}
                                    {% if section.images %}
                                        <div class="imageContainer">
                                            {% for image in section.images %}
                                                <img src="{{image.image.url}}" alt="">
                                            {% endfor %}
                                        </div>
                                        
                                    {% endif %}
                                    {% if section.section.text != "" %}
                                    <div class="sectionText">{{ section.section.text }}</div>
                                    {% endif %}
                                    {% if section.section.defaultModule %}
                                        <div class="defaultModuleWrapper">
                                            {% include section.section.defaultModule %}
                                        </div>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}

                            {% for question in questions %}
                                {% if question.question.position == i %}
                                    {% if question.type == 'short' %}
                                        <div class="questions">
                                            <h3>Question {{ forloop.counter }}</h3>
                                            <p>{{ question.question.question_text }}</p>
                                            <textarea
                                            rows="4"
                                            name="{{question.question.id}}"
                                            id="message"
                                            placeholder="Enter Answer Here!"
                                            class="textarea-input dynamicInput"
                                            ></textarea>
                                        </div>
                                    {% elif question.type == 'multi'%}
                                        <div class="questions">
                                            <h3>Question {{ forloop.counter }}</h3>
                                            <p>{{ question.question.question_text }}</p>
                                            {% if question.question.option1 %}
                                                <label>
                                                    <input type="radio" class="dynamicInput" name="{{question.question.id}}" value="1"> {{ question.question.option1 }}
                                                </label><br>
                                            {% endif %}
                                            {% if question.question.option2 %}
                                                <label>
                                                    <input type="radio" class="dynamicInput" name="{{question.question.id}}" value="2"> {{ question.question.option2 }}
                                                </label><br>
                                            {% endif %}
                                            {% if question.question.option3 %}
                                                <label>
                                                    <input type="radio" class="dynamicInput" name="{{question.question.id}}" value="3"> {{ question.question.option3 }}
                                                </label><br>
                                            {% endif %}
                                            {% if question.question.option4 %}
                                                <label>
                                                    <input type="radio" class="dynamicInput" name="{{question.question.id}}" value="4"> {{ question.question.option4 }}
                                                </label><br>
                                            {% endif %}
                                        </div>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                        
                        
                        <button id="submitbtn" class="btn">
                            Submit
                        </button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'students/js/moduleview.js' %}"></script>
{% endblock %}

mysite/students/templates/students/quizview.html
{% extends 'students/base.html' %}
{% load static %}

{% block title %}Elearn{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/quizview.css' %}">
{% endblock %}

{% block content %}
    <a class="backbtn" href="{% url 'students:quizHub' courseId%}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 18h3.75a5.25 5.25 0 1 0 0-10.5H5M7.5 4L4 7.5L7.5 11"/></svg></a>
    <a class="backbtn" id="homebtn" href="{% url 'students:course' courseId%}"><svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024"><path fill="currentColor" d="M946.5 505L534.6 93.4a31.93 31.93 0 0 0-45.2 0L77.5 505c-12 12-18.8 28.3-18.8 45.3c0 35.3 28.7 64 64 64h43.4V908c0 17.7 14.3 32 32 32H448V716h112v224h265.9c17.7 0 32-14.3 32-32V614.3h43.4c17 0 33.3-6.7 45.3-18.8c24.9-25 24.9-65.5-.1-90.5z"/></svg></a>

    <div id="contentwrapper">
        <div id="content">
            <div id="grade-wrapper" {% if not grade %}style="display: none;"{% endif %}>
                
                <h2>Attempt: {{attempt}}/{{quiz.attempts}} <br>
                    Your Grade: {{grade.grade}}%
                </h2>
                {% if attempt < quiz.attempts %}
                    <div class="btn" id="new-submission">New Submission</div>
                {% endif %}
            </div>
            <div id="wrapper" {% if grade %}style="display: none;"{% endif %}>
                <h2>{{quiz.title}}</h2>
                <div id="quiz-wrapper">
                    <form id="form" method="post">
                        {% csrf_token %}
                        {% for question in questions %}
                        <div class="questions">
                            <h3>Question {{ forloop.counter }}</h3>
                            <p>{{ question.question_text }}</p>
                            {% if question.option1 %}
                                <label>
                                    <input type="radio" name="{{question.id}}" value="1"> {{ question.option1 }}
                                </label><br>
                            {% endif %}
                            {% if question.option2 %}
                                <label>
                                    <input type="radio" name="{{question.id}}" value="2"> {{ question.option2 }}
                                </label><br>
                            {% endif %}
                            {% if question.option3 %}
                                <label>
                                    <input type="radio" name="{{question.id}}" value="3"> {{ question.option3 }}
                                </label><br>
                            {% endif %}
                            {% if question.option4 %}
                                <label>
                                    <input type="radio" name="{{question.id}}" value="4"> {{ question.option4 }}
                                </label><br>
                            {% endif %}
                        </div>

                    {% endfor %}
                    </form>
                </div>
                <button id="submitbtn" class="btn">
                    Submit
                </button>
            </div>
        </div>
    </div>

    <script src="{% static 'students/js/quiz.js' %}"></script>
{% endblock %}

mysite/students/templates/students/search.html
{% extends 'students/base.html' %}
{% load static %}

{% block title %}ELearn{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
{% endblock %}

{% block content %}
    <div id="contentwrapper">
        <div id="content">
            <div id="search">
                {% if classes %}
                    <h2>Courses</h2>
                    {% for class in classes %}
                        <div class="links">
                            <a href="{% url 'students:course' class.id %}">{{class.class_name}}</a>
                        </div>
                    {% endfor %}
                {% endif %}
                {% if quizzes %}
                    <h2>Quizzes</h2>
                    {% for quiz in quizzes %}
                        {% if quiz.is_visible %}
                            <div class="links">
                                <a href="{% url 'students:quizView' quiz.id quiz.course.id %}">{{quiz.title}}</a>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                {% if discussions %}
                    <h2>Discussions</h2>
                    {% for message in discussions %}
                        <div class="links">
                            <a href="{% url 'students:post' message.id message.course.id %}">{{message.subject}}</a>
                        </div>
                    {% endfor %}
                {% endif %}
                {% if not classes and not quizzes and not discussions %}
                    <span id="noresult">No Results for {{subject}}</span>
                {% endif %}
            </div>
            
        </div>
    </div>
{% endblock %}

mysite/students/templates/students/settings.html
{% extends 'students/base.html' %}
{% load static %}

{% block title %}Elearn{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/settings.css' %}">
{% endblock %}

{% block content %}
    <a class="backbtn" href="{{url}}"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 18h3.75a5.25 5.25 0 1 0 0-10.5H5M7.5 4L4 7.5L7.5 11"/></svg></a>
    <div id="contentwrapper">
        <div id="content">
            <div class="form-wrapper">
                <form method="post" action="{% url 'students:changeUsername' url %}">
                    {% csrf_token %}
                    <!-- Username change form fields here -->
                    <input class="textarea-input" type="text" name="new_username" placeholder="New Username">
                    <button class="btn" type="submit">Change Username</button>
                </form>
                
                <form method="post" action="{% url 'students:changePassword' url %}">
                    {% csrf_token %}
                    <input class="textarea-input" type="password" name="old_password" placeholder="Old Password">
                    <input class="textarea-input" type="password" name="new_password1" placeholder="New Password">
                    <input class="textarea-input" type="password" name="new_password2" placeholder="Confirm New Password">
                    <button class="btn" type="submit">Change Password</button>
                </form>
            </div>
            {% if messages %}

                {% for message in messages %}
                    {{message}}
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <script src="{% static 'teachers/js/quizhub.js' %}"></script>
{% endblock %}