mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", include("users.urls")),
    path("students/", include("students.urls", "students")),
    path("teachers/", include("teachers.urls", "teachers")),
    path('admin/', admin.site.urls),

    # DC - Forgotten Password URLS

    #1 - User Email Submission - Utilizes djangos PasswordResetView (class based view)
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="users/reset_password.html"), name="reset_password"),
    #2 - Email Sent Message - Utilizes django PasswordResetDoneView (class based view)
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="users/reset_password_sent.html"), name="password_reset_done"),
    #3 - Email Link + Reset Instructions - Utilizes PasswordResetConfirmView (class based view)
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/reset.html"), name="password_reset_confirm"),
    #4 - Password Successfully Reset - Utilizes PasswordResetCompleteView (class based view)
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="users/reset_password_complete.html"), name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path

from . import views
app_name = 'users'
urlpatterns = [
    path("register/", views.register, name="register"),
    path("", views.loginPage, name="loginPage"),
    path("logout/", views.logoutPage, name="logoutPage"),
]

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_teacher = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

mysite/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Account

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'username'}),
            'email': forms.EmailInput(attrs={'placeholder': 'email'}),
            'password1': forms.PasswordInput(render_value=True, attrs={'placeholder': 'Enter your password'}),
            'password2': forms.PasswordInput(render_value=True, attrs={'placeholder': 'Confirm your password'}),
        }

class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['is_teacher']
        

mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import Account
from django.contrib.auth.models import User
from .forms import CreateUserForm, AccountForm
from django.contrib import messages



def register(request):
    form = CreateUserForm()
    account_form = AccountForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        account_form = AccountForm(request.POST)
        if form.is_valid() and account_form.is_valid():
            user = form.save()
            account = account_form.save(commit=False)
            account.user = user
            account.save()
            return redirect('users:loginPage')
        else:
            messages.error(request, 'Could Not Register account')

    context = {'form':form, 'account_form':account_form}
    return render(request, "users/registration.html", context)

def loginPage(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = User.objects.get(username=username)
            account = Account.objects.get(user=user)
            if account is not None:
                auth = authenticate(request, username=username, password=password)
                if auth is not None:
                    is_teacher = account.is_teacher
                    login(request, user)
                    if is_teacher:
                        return redirect('teachers:home')
                    else:
                        return redirect('students:home')
                else:
                    messages.error(request, 'The Password is Incorrect')
        except Exception as e:
            messages.error(request, "The username does Not Exist")

    context = {}
    return render(request, "users/login.html", context)

def logoutPage(request):
    logout(request)
    return redirect('users:loginPage') 

mysite/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
  <h1>Stem Tree</h1>
  <div class="wrapper">
      <h2>Login</h2>
      <form method="POST" action="">
          {% csrf_token %}
        <div class="input-box">
          <input type="text" name="username" id="username" placeholder="Username" value="">
        </div>
        <div class="input-box">
          <input type="password" name="password" id="password" placeholder="Password" value="" >
        </div>
        <div class="input-box button">
          <input type="Submit" value="Login">
        </div>
        <div class="text">
          <h3>Need an account? <a href="{% url 'users:register' %}">Sign up now</a></h3>
          <h3>Forgot Password? <a href="{% url 'reset_password' %}">Reset Password</a></h3>
        </div>
      </form>
  </div>
  <div id="error-message">
    {% if messages %}

            {% for message in messages %}
                {{message}}
            {% endfor %}
    {% endif %}
  </div>
</body>
</html>

mysite/users/templates/users/registration.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Registration </title> 
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
   </head>
<body>
  <div class="wrapper">
    <h2>Registration</h2>
    <form method="POST" action="">
        {% csrf_token %}
      <div class="input-box">
        {{form.username}}
      </div>
      <div class="input-box">
        {{form.email}}
      </div>
      <div class="input-box">
        <input type="password" name="{{ form.password1.name }}" id="{{ form.password1.id_for_label }}" placeholder="Password" >
      </div>
      <div class="input-box">
        <input type="password" name="{{ form.password2.name }}" id="{{ form.password2.id_for_label }}" placeholder="Confirm Your Password" >
      </div>
      <div class="policy">
        {{account_form.is_teacher}}
        <h3>I Am A Teacher</h3>
      </div>
      <div class="input-box button">
        <input type="Submit" value="Register Now">
      </div>
      <div class="text">
        <h3>Already have an account? <a href="{% url 'users:loginPage' %}">Login now</a></h3>
      </div>
    </form>
  </div>
  <div id="error-message">
    {% if messages %}

            {% for message in messages %}
                {{message}}
            {% endfor %}
    {% endif %}
  </div>
</body>
</html>

mysite/users/templates/users/reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

{% block content %}
<h3>Enter new password</h3>
<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form class = "form" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" />
</form>

</html>

{% endblock content %}

mysite/users/templates/users/reset_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

{% block content %}
<h3>Password Reset</h3>
<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>

<form class = "form" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" />
</form>

</html>

{% endblock content %}

mysite/users/templates/users/reset_password_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

{% block content %}
<h3>Password reset complete</h3>
<p>Your password has been set. You may go ahead and log in now.</p>
<a href="{% url 'users:loginPage' %}">Login</a>
</html>

{% endblock content %}

mysite/users/templates/users/reset_password_sent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Reset</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

{% block content %}
<h3>Password reset sent</h3>
<p>Weve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly. If you dont receive an email, please make sure youve entered the address you registered with, and check your spam folder.</p>
</html>

{% endblock content %}